### ISSUE TITLE
Generate mock passport data from new signature algorithms

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/openpassport#107]
To add support for new signature algorithms, see https://github.com/zk-passport/proof-of-passport/issues/38, we need corresponding signed passport data. If you are not comfortable with sending us your passport data, you can always do the following: 
1. Build the app and read your passport
2. Write the passport data that has been logged in your console to a new json file, following [`mockPassportData.ts`](https://github.com/zk-passport/proof-of-passport/blob/main/common/src/utils/mockPassportData.ts).
3. Adapt a script in [`circuits/scripts/genMockPassportData`](https://github.com/zk-passport/proof-of-passport/blob/main/circuits/scripts/genMockPassportData) to generate a passport data file that is compliant with your signature algorithm.

If we don't already have mock data with your sig alg, we'll be happy to award you a bounty.

**Comment by juandiegocv27** [comment]
Hi,

**Comment by DevPelz** [comment]
I would like to work on this I believe my passport data hashing algorithm might be different

**Comment by remicolin** [comment]
Hi @juandiegocv27, @DevPelz, you can work on this.
First step is to scan your passport to know which hash/sig set-up is used.
Please let-us know when you got the information of you got any trouble building the app.

**Comment by DevPelz** [comment]
hi @remicolin I'm having issues building the app, how can I contact you?

**Comment by 0xturboblitz** [comment]
You can contact us on telegram at @colinremi and @FlorentTavernier

**Comment by DevPelz** [comment]
unable to dm, says i can only send messages to mutual contacts, do you mind sending me a dm @Devpelzz

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
Software engineering background with little contributions from previous od hacks

### How I plan on tackling this issue
I would follow all instructions as mentioned and deliver as soon as possible as this should not take much time

**Comment by LamsyA** [comment]
Hello @0xturboblitz, 

I am blockchain developer with over 2 years experience,  I am currently learning ZKPs and I have  recently worked on some projects using circom. I would to work on this issue as it looks interesting to me. Kindly assign it to me.

**Comment by Dedigraz** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I have worked on hashing algorithms before and this seems cool

### How I plan on tackling this issue
I would try it out with sha-512 and then rsa and aes if time permits.

**Comment by CrimsonKarma44** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I have 3 years of experience in backend programming in golang and python framework (django, flask)

### How I plan on tackling this issue
i will build the app from the repo locally populating it with passport details to generate a data file compliant with signature algorithm

**Comment by 0xturboblitz** [comment]
Mock passport data pipeline changed, this is not a priority anymore
