### ISSUE TITLE
Improve NFC reading UX on android

### ISSUE THREAD

**Issue by remicolin** [zk-passport/openpassport#130]
Issue Description:
when users scan their passport using NFC on Android, the following steps occur:

1. they click on the button "Scan with NFC" and a sheet opens at the bottom of the screen.
2. they hold their passport against their phone, moving it slowly until the NFC reader detects the chip in the passport.
3. when the NFC reader detects the chip, the phone vibrates, indicating that users should stop moving the phone.
4. once the passport reading is complete, the sheet closes, and the user is brought to the next screen.
<img width="379" alt="image" src="https://github.com/zk-passport/proof-of-passport/assets/98749896/8ecc671c-0b07-4bbb-9757-9bafbfb2f37d">

Problem:
the vibration alone is not sufficient to inform users that they need to stop moving the phone and that the phone is currently reading the chip.

Request:
we would like an implementation similar to the one on iOS, with an animation showing the progress of the reading and displaying which datagroup is currently being read.
<img width="452" alt="image" src="https://github.com/zk-passport/proof-of-passport/assets/98749896/9616cd98-3531-40d8-8a7b-3b6635322a55">

**Comment by Joy-Adah** [comment]
Hi @remicolin is this issue still available? I'd love to work on it.

**Comment by remicolin** [comment]
hi @Joy-Adah the issue is still available you can work on it

**Comment by Joy-Adah** [comment]
@remicolin thanks! I'll work on it

**Comment by remicolin** [comment]
do you have any updates to share @Joy-Adah ?

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
Hello, my name is Bernal. I am a software developer from Costa Rica. Currently, I work as a back-end developer. In my previous job, I worked as a full-stack developer. Personally, I enjoy developing both the back end and the front end. I have 4 years of experience in the software development industry. Some technologies I have worked with include: Typescript, React, C#, and Node.

### How I plan on tackling this issue
To reach the solution, the first step is to understand how the project works. This involves familiarizing yourself with the project's documentation, structure, and codebase. Next, thoroughly review the issue description to grasp the problem fully. Based on this understanding, brainstorm and propose a viable solution. Once you have a clear plan, implement the solution in the code. After coding, conduct comprehensive tests to ensure the fix resolves the issue without introducing new problems. Finally, review your changes and prepare them for submission, ensuring all aspects of the issue have been addressed effectively.

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I am a UI/UX designer with almost 2 years of experience, including work on Web 3 projects and various hackathons such as StarkNet and MuAccra. My expertise in creating intuitive and visually appealing user interfaces positions me well to address the current issue with the NFC passport scanning feature on Android.
I would like to contribute to this project.

Portfolio: https://www.figma.com/proto/HcFnqYWAab3sA4ws0oL8HL?node-id=16-2290&t=kNV6jRPoeTxuc3Lc-6

### How I plan on tackling this issue
I will analyze iOS implementation: I will review the iOS animation and progress indicators to understand the user experience.

And then I will design animation: Create a visually appealing animation that clearly indicates the progress of the NFC reading process.

Lastly, I will integrate feedback indicators: Display real-time updates on which datagroup is being read to keep users informed.

I'll also ensure the implementation works seamlessly across different Android devices and screen sizes.

**Comment by remicolin** [comment]
@BernalHQ can you give me a human written version of how you plan to tackle the issue?

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
Hello @remicolin,

I have experience as a mobile developer with Dart, Flutter and those technologies and I know how to test, debug and measure all this procceses using Android Studio, considering this is an issue related with Android I think I could have a good backgroud to work on it and I'm part of the Dojo community in Costa Rica.

### How I plan on tackling this issue
Approach to Resolve the Issue:

- Visual Progress Animation: Implement a visual progress animation to indicate the reading process. This will provide clear feedback to users about the ongoing reading and when to stop moving the phone.

- DataGroup Display: Display which datagroup is being read during the NFC process. This enhances user understanding and engagement.

- Integration and Testing: Integrate these visual cues into the existing Android NFC scanning workflow. Thoroughly test and debug using Android Studio to ensure smooth functionality across devices.

- Variable Investigation: Investigate if there is a value or variable that updates during the reading process to create the animation. Implementing the animation will be straightforward once this detail is identified.

Also I could work on this one together with @BernalHQ, to have discussions, more ideas and done it in a quickly way too.

**Comment by remicolin** [comment]
@BernalHQ sweet, you can start working on it!
if you want i can provide you screen recording of the iOS version which is basically empty dots that turn green.
feel free to dm on tg @colinremi

**Comment by BernalHQ** [comment]
Hi @remicolin, thanks for the oportunity. I going to start work it on it. And yes, please provide me a example of the IOS version animation.

**Comment by eliotstock** [comment]
Is this fixed? I can't scan either of my passports on Android. Using a Pixel 8.
