### ISSUE TITLE
Date entry on manual verification is very unintuitive 

### ISSUE THREAD

**Issue by sarahwooders** [zk-passport/openpassport#148]
I had some issues entering manual verification: 
* the date entry is very unintuitive (I've never seen `yymmdd` before) so I almost messed it up 
* there is no confirmation that the manual verification has been entered - the boxes just turn green

**Comment by remicolin** [comment]
thanks for the feedback, a date picker is now available along with a toast message when field have all been entered on the us-election branch.
for the dev branch it will be merged with #149 (tamagui stuff to fix before merge)

looks like this

![Screenshot 2024-07-17 at 12 56 17](https://github.com/user-attachments/assets/11f99456-3765-4856-925e-3992c2fdc5fb)
