### ISSUE TITLE
Modal service for zkey generation

### ISSUE THREAD

**Issue by remicolin** [zk-passport/openpassport#164]
some zkeys are really long to build (especially for the dsc circuits) and ecdsa related ones will require more capabilities than mac allows.
A good idea would be to build them on a [modal](https://modal.com/docs) server such as we do for the [dsc proving](https://github.com/zk-passport/proof-of-passport/tree/dev/prover) 
I would probably look into [zk-email codebase](https://github.com/orgs/zkemail/repositories)

**Comment by MPSxDev** [comment]
I would be happy to work on this issue. 
In zk-email they used a mix of modal.com and aws for storage.
We could implement something similar. @remicolin
