### ISSUE TITLE
Refactor generateCircuitInputsRegister with ecdsa circuit inputs

### ISSUE THREAD

**Issue by remicolin** [zk-passport/openpassport#166]
generateCircuitInputsRegister is the function used to generate the inputs of register circuit, which verify the signature of a passport.
ecdsa signature verification has been implemented on dev branch, but the generation of the inputs are achieved locally in the test sheet.
we want generateCircuitInputsRegister to be generic and to return the right circuits inputs according to the passport data passed in the function, more specifically to the sig alg

**Comment by 0xturboblitz** [comment]
Done [here](https://github.com/zk-passport/openpassport/commit/e98937cfd307c5c95b77e2ef3990b9843b795574)
