### ISSUE TITLE
Remove `signatureAlgorithm` and `pubKey` from `PassportData` type

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/openpassport#182]
We only want to keep `dsc` in `PassportData`. This is cleaner and we have nice functions to get the signature algorithm, hash function, hash length, etc from it.

Some scripts from `common/scripts/passportData` don't use DSCs but generate pubkeys manually. I added a mock ECDSA DSC generated from [here](https://www.golinuxcloud.com/generate-self-signed-certificate-openssl) and adapted `sha256_ecdsa.ts` as an example, but this should be done on other scripts. Once this is done, we can remove `pubKey` and `signatureAlgorithm` and always use `getSignatureAlgorithm`, `getCircuitName`, etc

Also, the ecdsa scripts in `common/scripts/passportData` still use `node` specific imports, so can't be added to the mock passport data generator in the app. The adaptation I made above works without node, so it will solve that too.

**Comment by Iwueseiter** [comment]
Hi @0xturboblitz can I work on this?

**Comment by 0xturboblitz** [comment]
> Hi @0xturboblitz can I work on this?

This one is outside the scope of onlydust contributions
