### ISSUE TITLE
How can you prove the ID is correct (existing)?

### ISSUE THREAD

**Issue by kopeboy** [zk-passport/openpassport#184]
How can you prove the passport is valid without calling an API for each issuer Country and getting affirmative response?

**Comment by 0xturboblitz** [comment]
Because the data in passports is signed and public keys are available online. You can find out more about it by looking for documentation on e-passports.

**Comment by kopeboy** [comment]
Right, sorry for the noob question 😅 I should have known it, basic cryptography
