### ISSUE TITLE
use a more specific/restrictive type for `userId`

### ISSUE THREAD

**Issue by sripwoud** [zk-passport/openpassport#186]
I just encountered a bug when trying for the first time to use the `OpenPassportQRcode` components.  
(Quickly solved thanks to direct support from @remicolin ).

This issue is just to capture/discuss a potential improvement on the typing of the `userId` component prop.
https://github.com/zk-passport/openpassport/blob/7aba22edf4ceaa6259aef4a0984dd54bb821fcb2/sdk/src/QRcode/OpenPassportQRcode.d.ts#L6

Remi explained me that it can't actually be any string. but only hexifiable strings, so that it can be used as a signal for the circuit.  

It would be nice to have either a runtime check/validation or a better TS type to avoid that devs naively put any string.
Eg the [type of UUID](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85536d638d1703c2c00f258d1dcc0794b668f0c2/types/node/crypto.d.ts#L3497)?

E.g I[ had used my username at first](https://github.com/sripwoud/hello-openpassport/commit/27555a8a8ed269ae94a93e0ba597ac353e0a617e). It resulted in a error: `reference Error: document is undefined`

**Comment by remicolin** [comment]
@sripwoud thanks for opening the issue.
[UUID](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85536d638d1703c2c00f258d1dcc0794b668f0c2/types/node/crypto.d.ts#L3497) and hexifiable strings are indeed the only type supported for now (with hexifiable strings).

I just raised #187 that fix the issue, a new version of the sdk is already available, we still need to push a new version of the app to the store to parse the string userId in the inputs of the circuit correctly.

Please note that max length of the userId for type string is capped by the use of BN254, i wrote more details about it [here](https://docs.openpassport.app/docs/use-openpassport/quickstart)
