### ISSUE TITLE
Not able to build `@openpassport/sdk` using deno

### ISSUE THREAD

**Issue by 0xisk** [zk-passport/openpassport#190]
Hey! 
I was trying to build a wrapper for `@openpassport/sdk` using Deno to be able to make it work in a rust project. 
But I got this issue: 

```
deno run --unstable --allow-read=node_modules --allow-net openPassportVerifier.ts                     ✔  18.16.1  

⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: Error in @openpassport/sdk@0.1.7 parsing version requirement for dependency: node-forge@git+https://github.com/remicolin/forge.git

Invalid npm version requirement. Unexpected character.
  git+https://github.com/remicolin/forge.git
  ~
    at file:///home/isk/projects/pse/hackathon_2024/snark-verifier-server-rs/deno/src/openPassportVerifier.ts:1:96
```

```ts
// openPassportVerifier.ts
import { OpenPassport1StepInputs, OpenPassportVerifierReport, OpenPassport1StepVerifier } from 'npm:@openpassport/sdk@^0.1.7';

let verifier: OpenPassport1StepVerifier | null = null;

export function initializeVerifier(options: {
    scope: string;
    attestationId?: string;
    requirements?: string[][];
    rpcUrl?: string;
    dev_mode?: boolean;
}): void {
    verifier = new OpenPassport1StepVerifier(options);
}

export async function verifyPassport(openPassport1StepInputs: OpenPassport1StepInputs): Promise<OpenPassportVerifierReport> {
    if (!verifier) {
        throw new Error("Verifier has not been initialized. Please call initializeVerifier first.");
    }
    return await verifier.verify(openPassport1StepInputs);
}
```

**Related Project**: https://github.com/dog-18/openpassport-rs

**Comment by 0xturboblitz** [comment]
looks like deno doesn't like [this github link](https://github.com/zk-passport/openpassport/blob/6aca335c120864fa7bab662c070a4b17a21bd408/sdk/package.json#L26) as a package identifier. Not familiar with deno, does it support anything different from npm as sources? @0xisk

**Comment by 0xisk** [comment]
> @remicolin
> 
> looks like deno doesn't like [this github link](https://github.com/zk-passport/openpassport/blob/6aca335c120864fa7bab662c070a4b17a21bd408/sdk/package.json#L26) as a package identifier. Not familiar with deno, does it support anything different from npm as sources? @0xisk

Thanks @0xturboblitz for your fast reply. I am not experienced with Deno, but I guess if you could publish your forked version in NPM that would be the easiest.
