### ISSUE TITLE
Add nationality set inclusion check to circuit

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/openpassport#56]
Some actors from traditional finance can't enter decentralised finance because of the lack of enforceable regulation. For instance, legislation prevents them from dealing with users from certain countries, but they have no way of checking reliably the nationality of users and heuristics such as IP address are not reliable enough.

Proof of passport could allow users to prove they are not citizens of a given subset of countries without revealing their nationality.

This would involve writing a disclosure circuit that extract the nationality and does an (non-)inclusion check over a group of countries.

Depending on the size and complexity of the circuit, this could be integrated in the main `disclose.circom` or be a separate disclosure circuit.

I think you would do it by passing the root of a sparse merkle tree representing a list of countries as a public input and do a inclusion check or a non-inclusion check in the circuit.

This system could be reused for https://github.com/zk-passport/proof-of-passport/issues/120

**Comment by Dprof-in-tech** [comment]
Hello @0xturboblitz 
I'm Isaac a javascript developer with notable experience contributing to web3 projects on the OnlyDust platform.

I would love to work on this issue and I would tackle it by setting up a dataset of blacklisted countries, implementing a method whereby a user generates a zkproof that they are not a citizen of a blacklisted country without revealing their identity, and comparing this proof with blacklisted countries granting access to users who meet the requirements.

i would be awaiting your response.
Thank you

**Comment by remicolin** [comment]
Hi @Dprof-in-tech, do you have experience building circom circuits?

**Comment by Dprof-in-tech** [comment]
This would be my first time working with the circom library but I believe it would be a good learning experience

**Comment by 0xturboblitz** [comment]
For for it then, and feel free to dm if you have questions

**Comment by Dprof-in-tech** [comment]
hi @0xturboblitz , i'm trying to set up the project on my local computer and i think i would need help with that
can't find you on the telegram group so i can send a dm

**Comment by Dprof-in-tech** [comment]
hi @0xturboblitz i just set up the project on my local machine

**Comment by rajeshkumarrobert** [comment]
@0xturboblitz I like to work on this, I'm a beginner in circom and I hope I can complete this

**Comment by 0xturboblitz** [comment]
Hi @rajeshkumarrobert, go for it and feel free to dm if you have questions

**Comment by sBaki92** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
Hi!
I am a freshman in the Starknet ecosystem. I've completed two Basecamps and the latest HackerHouse, and I would like to have this issue assigned to me so I can apply everything I've learned.

**Comment by the-first-elder** [comment]
Looks interesting would love to do this

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
software enginnering background and have worked on a similar project from contribution in previous odhacks and i'm confident in working on this

### How I plan on tackling this issue
I would work on extracting the nationality and performing a check on the tree of countries representing the input countries as highlighted. This should take only a short while

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I'd like to work on the issue: Add nationality set inclusion check to circuit. I've been learning Circom in a ZK program by PSE and have backend development experience. I'm eager to start contributing to Proof of Passport.

### How I plan on tackling this issue
This could be my general approach:
Circuit Design: I will write a disclosure circuit to extract nationality.
Merkle Tree: I will pass the root of a sparse Merkle tree representing the list of countries as a public input.
Inclusion/Non-Inclusion Check: I will implement the check within the circuit.

**Comment by PavitraAgarwal21** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
Hi, first of all, great project! To introduce myself, I have experience writing Circom circuits, particularly some what related to TornadoCash circuit . I used the nullifier and commitment hash components to verify tickets in a project that won the StarkNet hackathon. Additionally, I utilized their Merkle tree to verify if a person is whitelisted. You can check my GitHub repo for ZKTPS in the circuit section. I also have an in-depth understanding of how proof systems work, although it might not be directly required here.

### How I plan on tackling this issue
First of all i think , what we have to do is to make the merkle root from the data through ofsn sdn webiste  using  any python library out there (easy to do with csv also ). Once the merkle root is created what we have to do is to  make circuit which check the user country is not in the merkle tree , this is similar to the merkle tree proof circuit which is in the many of solution like in the tornadocash it use for the checking of the whitelisting of the users , in this we have to check the non inclusion so it have some changes  like we can have to  ensure that the leaf is not equal to any of the path elements (sibling nodes ) which  indicating non-inclusion . then i think all thing is similar to the merkle root proving circuit .

**Comment by 0xturboblitz** [comment]
will assign to @ashpect as we worked on similar things in https://github.com/zk-passport/proof-of-passport/issues/120

**Comment by ashpect** [comment]
> will assign to @ashpect as we worked on similar things in #120

Will be happy to work on this as well.

**Comment by ashpect** [comment]
@0xturboblitz #175
